version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: chat-backend
    restart: unless-stopped
    ports:
      - "5004:5004"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - chat-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5004"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: chat-frontend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - REACT_APP_API_URL=http://localhost:5004
      - HOST=0.0.0.0
      - WDS_SOCKET_PORT=0
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge
    name: chat-network 